export const mockItems = [
    {
      _id: "item1",
      name: "Professional Camera",
      category: "Electronics",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "High-quality professional camera with multiple lenses and accessories.",
      price: 500000,
      rate: "day",
      isFree: false,
      ownerClerkId: "user123",
      status: "available",
      createdAt: "2023-01-15T08:30:00.000Z",
    },
    {
      _id: "item2",
      name: "Mountain Bike",
      category: "Sports",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Premium mountain bike for off-road adventures.",
      price: 300000,
      rate: "day",
      isFree: false,
      ownerClerkId: "user456",
      status: "available",
      createdAt: "2023-02-20T10:15:00.000Z",
    },
    {
      _id: "item3",
      name: "Drill Machine",
      category: "Tools",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Powerful drill machine for home improvement projects.",
      price: 150000,
      rate: "hour",
      isFree: false,
      ownerClerkId: "user789",
      status: "notAvailable",
      createdAt: "2023-03-05T14:45:00.000Z",
    },
    {
      _id: "item4",
      name: "Camping Tent",
      category: "Sports",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Spacious 4-person camping tent, waterproof and easy to set up.",
      price: 250000,
      rate: "day",
      isFree: false,
      ownerClerkId: "user123",
      status: "available",
      createdAt: "2023-03-10T09:20:00.000Z",
    },
    {
      _id: "item5",
      name: "Acoustic Guitar",
      category: "Music",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Beautiful acoustic guitar with great sound quality.",
      price: 200000,
      rate: "day",
      isFree: false,
      ownerClerkId: "user456",
      status: "available",
      createdAt: "2023-04-15T11:30:00.000Z",
    },
    {
      _id: "item6",
      name: "Projector",
      category: "Electronics",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "HD projector for home theater or presentations.",
      price: 350000,
      rate: "day",
      isFree: false,
      ownerClerkId: "user789",
      status: "available",
      createdAt: "2023-05-02T16:10:00.000Z",
    },
    {
      _id: "item7",
      name: "Board Games Collection",
      category: "Entertainment",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Collection of popular board games for family fun.",
      price: 0,
      rate: "day",
      isFree: true,
      ownerClerkId: "user123",
      status: "available",
      createdAt: "2023-05-20T13:45:00.000Z",
    },
    {
      _id: "item8",
      name: "Lawn Mower",
      category: "Tools",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Electric lawn mower for garden maintenance.",
      price: 180000,
      rate: "hour",
      isFree: false,
      ownerClerkId: "user456",
      status: "notAvailable",
      createdAt: "2023-06-05T08:15:00.000Z",
    },
    {
      _id: "item9",
      name: "Kayak",
      category: "Sports",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Single-person kayak for lake or river adventures.",
      price: 400000,
      rate: "day",
      isFree: false,
      ownerClerkId: "user789",
      status: "available",
      createdAt: "2023-06-18T10:30:00.000Z",
    },
    {
      _id: "item10",
      name: "Drone",
      category: "Electronics",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Professional drone with 4K camera for aerial photography.",
      price: 600000,
      rate: "day",
      isFree: false,
      ownerClerkId: "user123",
      status: "available",
      createdAt: "2023-07-01T15:20:00.000Z",
    },
    {
      _id: "item11",
      name: "Party Speakers",
      category: "Electronics",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Powerful speakers for parties and events.",
      price: 250000,
      rate: "day",
      isFree: false,
      ownerClerkId: "user456",
      status: "available",
      createdAt: "2023-07-15T12:10:00.000Z",
    },
    {
      _id: "item12",
      name: "Pressure Washer",
      category: "Tools",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "High-pressure washer for cleaning outdoor surfaces.",
      price: 200000,
      rate: "hour",
      isFree: false,
      ownerClerkId: "user789",
      status: "available",
      createdAt: "2023-08-02T09:45:00.000Z",
    },
    {
      _id: "item13",
      name: "Sewing Machine",
      category: "Crafts",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Modern sewing machine for clothing and craft projects.",
      price: 150000,
      rate: "day",
      isFree: false,
      ownerClerkId: "user123",
      status: "notAvailable",
      createdAt: "2023-08-20T14:30:00.000Z",
    },
    {
      _id: "item14",
      name: "Bicycle Child Seat",
      category: "Sports",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Safe and comfortable child seat for bicycles.",
      price: 0,
      rate: "day",
      isFree: true,
      ownerClerkId: "user456",
      status: "available",
      createdAt: "2023-09-05T11:15:00.000Z",
    },
    {
      _id: "item15",
      name: "Ladder",
      category: "Tools",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Extendable aluminum ladder for home and garden use.",
      price: 120000,
      rate: "day",
      isFree: false,
      ownerClerkId: "user789",
      status: "available",
      createdAt: "2023-09-18T10:00:00.000Z",
    },
    {
      _id: "item16",
      name: "Snowboard",
      category: "Sports",
      images: ["/placeholder.svg?height=200&width=300"],
      description: "Professional snowboard for winter sports enthusiasts.",
      price: 350000,
      rate: "day",
      isFree: false,
      ownerClerkId: "user123",
      status: "available",
      createdAt: "2023-10-01T13:45:00.000Z",
    },
  ]
  