name: main workflow
on:
  pull_request:
    types: [opened]
  push:
    branches-ignore:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "please wait for TranToan25092003 review your code 游때游때游때游때"
